name: Environment test 2
on:
  push:
    branches: "kyanny-patch-1"
  workflow_dispatch:
jobs:
  testjob:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Read production environment secret
        env:
          MY_PRODUCTION_SECRET_ENV: ${{secrets.MY_PRODUCTION_SECRET}}
        run: |
          echo start
          echo $MY_PRODUCTION_SECRET_ENV | sed -E 's/(.)/\1 /g'
          echo end
